// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: pkg/messaging/record.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordData holds data of a record
type RecordData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Value        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordData) Reset() {
	*x = RecordData{}
	mi := &file_pkg_messaging_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordData) ProtoMessage() {}

func (x *RecordData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_messaging_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordData.ProtoReflect.Descriptor instead.
func (*RecordData) Descriptor() ([]byte, []int) {
	return file_pkg_messaging_record_proto_rawDescGZIP(), []int{0}
}

func (x *RecordData) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

// Metadata contains metadata for a data record, such as timestamps and stream
// time.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Record received date in Unix timestamp
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`       // Name of the stream the record belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pkg_messaging_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_messaging_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pkg_messaging_record_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metadata) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// Record represents a single data record in the stream.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`           // Key for the record
	Data          *RecordData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // Data of the record
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // Metadata for the record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pkg_messaging_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_messaging_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pkg_messaging_record_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetData() *RecordData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Record) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request message to initiate stream
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_pkg_messaging_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_messaging_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_messaging_record_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_pkg_messaging_record_proto protoreflect.FileDescriptor

const file_pkg_messaging_record_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/messaging/record.proto\x12\tmessaging\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\n" +
	"RecordData\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04data\"\\\n" +
	"\bMetadata\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\"v\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.messaging.RecordDataR\x04data\x12/\n" +
	"\bmetadata\x18\x03 \x01(\v2\x13.messaging.MetadataR\bmetadata\"(\n" +
	"\rStreamRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2N\n" +
	"\fRecordStream\x12>\n" +
	"\rStreamRecords\x12\x18.messaging.StreamRequest\x1a\x11.messaging.Record0\x01B\x12Z\x10./pkg/messaging/b\x06proto3"

var (
	file_pkg_messaging_record_proto_rawDescOnce sync.Once
	file_pkg_messaging_record_proto_rawDescData []byte
)

func file_pkg_messaging_record_proto_rawDescGZIP() []byte {
	file_pkg_messaging_record_proto_rawDescOnce.Do(func() {
		file_pkg_messaging_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_messaging_record_proto_rawDesc), len(file_pkg_messaging_record_proto_rawDesc)))
	})
	return file_pkg_messaging_record_proto_rawDescData
}

var file_pkg_messaging_record_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_messaging_record_proto_goTypes = []any{
	(*RecordData)(nil),            // 0: messaging.RecordData
	(*Metadata)(nil),              // 1: messaging.Metadata
	(*Record)(nil),                // 2: messaging.Record
	(*StreamRequest)(nil),         // 3: messaging.StreamRequest
	(*structpb.Value)(nil),        // 4: google.protobuf.Value
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_pkg_messaging_record_proto_depIdxs = []int32{
	4, // 0: messaging.RecordData.data:type_name -> google.protobuf.Value
	5, // 1: messaging.Metadata.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: messaging.Record.data:type_name -> messaging.RecordData
	1, // 3: messaging.Record.metadata:type_name -> messaging.Metadata
	3, // 4: messaging.RecordStream.StreamRecords:input_type -> messaging.StreamRequest
	2, // 5: messaging.RecordStream.StreamRecords:output_type -> messaging.Record
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_messaging_record_proto_init() }
func file_pkg_messaging_record_proto_init() {
	if File_pkg_messaging_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_messaging_record_proto_rawDesc), len(file_pkg_messaging_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_messaging_record_proto_goTypes,
		DependencyIndexes: file_pkg_messaging_record_proto_depIdxs,
		MessageInfos:      file_pkg_messaging_record_proto_msgTypes,
	}.Build()
	File_pkg_messaging_record_proto = out.File
	file_pkg_messaging_record_proto_goTypes = nil
	file_pkg_messaging_record_proto_depIdxs = nil
}
